### ISSUE TITLE
Listing this repo on PZ third party envs

### ISSUE THREAD

**Issue by jjshoots** [NullDefault/Gym-Stag-Hunt#3]
Hiya,

I'm part of the PettingZoo maintenance team. We're a big fan of your environment, and was wondering if you'd like to have it put on [the official PettingZoo's third party env list](https://www.pettingzoo.ml/third_party_envs), which can be edited [here](https://github.com/Farama-Foundation/PettingZoo/blob/website/docs/third_party_envs.md).

**Comment by NullDefault** [comment]
Absolutely! I'd be honored! Should I open a PR, or can that be taken care of by the maintenance team?

**Comment by jjshoots** [comment]
If you can open a PR, all the better. Especially since you're better at describing what this env does than us. :)

**Comment by NullDefault** [comment]
Will do tomorrow! Super excited about this - really did not expect this, so I am over the moon!
